# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data": "01_image_classification.ipynb"}

modules = ["introduction.py",
           "image_classification.py"]

doc_url = "https://fastai.github.io/ai_workshops/"

git_url = "https://github.com/fastai/ai_workshops/tree/master/"

def custom_doc_links(name): return None
