# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://aida-uiuc.github.io/ai_workshops/"

git_url = "https://github.com/aida-uiuc/ai_workshops/tree/master/"

def custom_doc_links(name): return None
