# AUTOGENERATED! DO NOT EDIT! File to edit: 01_image_classification.ipynb (unless otherwise specified).

__all__ = ['data']

# Cell
import numpy as np

# Cell
from fastai.vision.all import *

# Cell
data = DataBlock(blocks = (ImageBlock, CategoryBlock),
                 get_items = get_image_files,
                 get_y = parent_label,
                 splitter = GrandparentSplitter(valid_name='val'),
                 item_tfms = RandomResizedCrop(128, min_scale=0.35),
                 batch_tfms = Normalize.from_stats(*imagenet_stats)
                )